# Generated by Django 4.2.27 on 2026-01-13 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Snapshot Name')),
                ('blockchain_data', models.JSONField(verbose_name='Blockchain Data')),
                ('difficulty', models.IntegerField(verbose_name='Difficulty Level')),
                ('mining_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mining Reward')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blockchain Snapshot',
                'verbose_name_plural': 'Blockchain Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=500, verbose_name='From Address')),
                ('to_address', models.CharField(max_length=500, verbose_name='To Address')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('signature', models.TextField(verbose_name='Digital Signature')),
                ('is_mined', models.BooleanField(default=False, verbose_name='Is Mined')),
                ('block_index', models.IntegerField(blank=True, null=True, verbose_name='Block Index')),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=500, unique=True, verbose_name='Public Key (Address)')),
                ('private_key', models.CharField(max_length=500, verbose_name='Private Key')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wallet Label')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-created_at'],
            },
        ),
    ]
